code --install-extension aaron-bond.better-comments
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension CS128.lldb-debugger-args-escape-tool
code --install-extension cschlosser.doxdocgen
code --install-extension dariofuzinato.vue-peek
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension ericsonj.verilogformat
code --install-extension evzen-wybitul.magic-racket
code --install-extension formulahendry.code-runner
code --install-extension Gimly81.matlab
code --install-extension GitHub.copilot
code --install-extension GitHub.vscode-pull-request-github
code --install-extension golang.go
code --install-extension haskell.haskell
code --install-extension Ikuyadeu.r
code --install-extension James-Yu.latex-workshop
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension justusadam.language-haskell
code --install-extension magicstack.MagicPython
code --install-extension martinring.smt-lib-syntax
code --install-extension mechatroner.rainbow-csv
code --install-extension mikestead.dotenv
code --install-extension mrob95.vscode-talonscript
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.hexeditor
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension mshr-h.veriloghdl
code --install-extension notskm.clang-tidy
code --install-extension octref.vetur
code --install-extension oderwat.indent-rainbow
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension REditorSupport.r-lsp
code --install-extension rust-lang.rust
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension skyapps.fish-vscode
code --install-extension steoates.autoimport
code --install-extension twxs.cmake
code --install-extension vadimcn.vscode-lldb
code --install-extension vasilescur.better-mips
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscode-icons-team.vscode-icons
code --install-extension xaver.clang-format
code --install-extension yzhang.markdown-all-in-one
