code --install-extension aaron-bond.better-comments
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dariofuzinato.vue-peek
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension evzen-wybitul.magic-racket
code --install-extension golang.go
code --install-extension Ikuyadeu.r
code --install-extension magicstack.MagicPython
code --install-extension mechatroner.rainbow-csv
code --install-extension mikestead.dotenv
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode.cpptools
code --install-extension octref.vetur
code --install-extension oderwat.indent-rainbow
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension REditorSupport.r-lsp
code --install-extension steoates.autoimport
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscode-icons-team.vscode-icons
